import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { MatButtonModule } from '@angular/material/button';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatListModule } from '@angular/material/list';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatIconModule } from '@angular/material/icon'
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field'
import {MatGridListModule} from '@angular/material/grid-list';
import {MatTabsModule} from '@angular/material/tabs';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { TodoService } from './services/todo.service';

import { HTTP_INTERCEPTORS, HttpClientModule } from '@angular/common/http';
import { IPublicClientApplication, PublicClientApplication, InteractionType } from '@azure/msal-browser';
import {
    MsalGuard, MsalInterceptor, MsalBroadcastService, MsalInterceptorConfiguration, MsalModule, MsalService,
    MSAL_GUARD_CONFIG, MSAL_INSTANCE, MSAL_INTERCEPTOR_CONFIG, MsalGuardConfiguration, MsalRedirectComponent, ProtectedResourceScopes
} from '@azure/msal-angular';

import { msalConfig, loginRequest, protectedResources } from './auth-config';
import { ExpenseGroupDetailsComponent } from './components/ExpenseGroups/expense-group-details/expense-group-details.component';
import { ExpenseGroupAddComponent } from './components/ExpenseGroups/expense-group-add/expense-group-add.component';
import { ExpenseGroupListComponent } from './components/ExpenseGroups/expense-group-list/expense-group-list.component';
import { InvitationsAddComponent } from './components/Invitations/invitations-add/invitations-add.component';
import { ExpenseGroupService } from './services/expenseGroup.service';
import { InvitationService } from './services/invitations.service';
import { ExpenseGroupClient, InvitationClient } from './services/HttpClients/autogeneratedClient';
import { InvitationsListComponent } from './components/Invitations/invitations-list/invitations-list.component';

/**
 * Here we pass the configuration parameters to create an MSAL instance.
 * For more info, visit: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md
 */
export function MSALInstanceFactory(): IPublicClientApplication {
    return new PublicClientApplication(msalConfig);
}

/**
 * MSAL Angular will automatically retrieve tokens for resources
 * added to protectedResourceMap. For more info, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/initialization.md#get-tokens-for-web-api-calls
 */
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string | ProtectedResourceScopes> | null>();

    protectedResourceMap.set(protectedResources.apiTodoList.endpoint, [
         {
             httpMethod: 'GET',
             scopes: [...protectedResources.apiTodoList.scopes.read]
         },
         // {
         //     httpMethod: 'POST',
         //     scopes: [...protectedResources.apiTodoList.scopes.write]
         // },
         // {
         //     httpMethod: 'PUT',
         //     scopes: [...protectedResources.apiTodoList.scopes.write]
         // },
         // {
         //     httpMethod: 'DELETE',
         //     scopes: [...protectedResources.apiTodoList.scopes.write]
         // }
    ]);

    return {
        interactionType: InteractionType.Popup,
        protectedResourceMap,
    };
}

/**
 * Set your default interaction type for MSALGuard here. If you have any
 * additional scopes you want the user to consent upon login, add them here as well.
 */
export function MSALGuardConfigFactory(): MsalGuardConfiguration {
    return {
        interactionType: InteractionType.Redirect,
        authRequest: loginRequest
    };
}

@NgModule({
    declarations: [
        AppComponent,
        HomeComponent,
        ExpenseGroupDetailsComponent,
        ExpenseGroupAddComponent,
        ExpenseGroupListComponent,
        InvitationsAddComponent,
        InvitationsListComponent
    ],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        AppRoutingModule,
        MatButtonModule,
        MatToolbarModule,
        MatGridListModule,
        MatListModule,
        MatTableModule,
        MatCardModule,
        MatTabsModule,
        MatInputModule,
        MatFormFieldModule,
        MatCheckboxModule,
        MatIconModule,
        HttpClientModule,
        FormsModule,
        MsalModule
    ],
    providers: [
        {
            provide: HTTP_INTERCEPTORS,
            useClass: MsalInterceptor,
            multi: true
        },
        {
            provide: MSAL_INSTANCE,
            useFactory: MSALInstanceFactory
        },
        {
            provide: MSAL_GUARD_CONFIG,
            useFactory: MSALGuardConfigFactory
        },
        {
            provide: MSAL_INTERCEPTOR_CONFIG,
            useFactory: MSALInterceptorConfigFactory
        },
        MsalService,
        MsalGuard,
        MsalBroadcastService,
        TodoService,
        ExpenseGroupService,
        InvitationService,
        ExpenseGroupClient,
        InvitationClient
    ],
    bootstrap: [AppComponent, MsalRedirectComponent]
})
export class AppModule { }
