import { Component, OnInit } from '@angular/core';
import { InvitationClient, InvitationResponse } from 'src/app/services/HttpClients/autogeneratedClient';
import {MatTableDataSource} from "@angular/material/table"

@Component({
  selector: 'app-invitations-list',
  templateUrl: './invitations-list.component.html',
  styleUrls: ['./invitations-list.component.css']
})
export class InvitationsListComponent implements OnInit {

  public RecievedInvitations: InvitationResponse[] | [] = [];
  public SentInvitations:InvitationResponse[] | [] = [];

  //public displayedColumns = ["Group name", "From", "Amount expensed", "Status", "Date sent"] 
  public displayedColumns = ["acceptance", "expenseGroupId", "invitationProfileId", "profileId"] 

  constructor(private invitationClient:InvitationClient) { }

  ngOnInit(): void {
    this.getRecievedInvitations();
    this.getSentInvitations();
  }

  private getRecievedInvitations():void{
    this.invitationClient.getRecievedInvitations().subscribe((response)=>{
      this.RecievedInvitations = response;
      console.log(response);
    })
  }

  private getSentInvitations(){
    this.invitationClient.getSentInvitations().subscribe((response) => {
      this.SentInvitations = response;
      console.log(response);
    })
  }

}
