import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observable } from 'rxjs';
import { ExpenseGroupService } from 'src/app/services/expenseGroup.service';
import { ExpenseGroup, ExpenseGroupClient } from 'src/app/services/HttpClients/autogeneratedClient';

@Component({
  selector: 'app-expense-group-list',
  templateUrl: './expense-group-list.component.html',
  styleUrls: ['./expense-group-list.component.css']
})
export class ExpenseGroupListComponent implements OnInit {

  expenseGroups:ExpenseGroup[] | undefined;

  constructor(private route: ActivatedRoute, private router: Router, private service: ExpenseGroupService, private expenseGroupClient: ExpenseGroupClient) {

  }

  // editTodo(todo: Todo): void {
  //     this.todo.description = todo.description;
  //     this.service.editTodo(this.todo).subscribe(() => {
  //         this.router.navigate(['/todo-view']);
  //     })
  // }

  

  ngOnInit(): void {
    this.getExpenseGroups();

    // this.route.paramMap.subscribe((params) => {
    //     let id = +params.get('id')!;
    //     this.service.getTodo(+id).subscribe((response: Todo) => {
    //         this.todo = response;
    //     })
    // })

  }

  private getExpenseGroups() : void {
    this.expenseGroupClient.getAllWithDetails().subscribe((response) => {
      this.expenseGroups = response;
    })
  }

}
