// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TGC.CareShare.WebAPI.Repositories;

#nullable disable

namespace TGC.CareShare.WebAPI.Migrations
{
    [DbContext(typeof(CareShareDBContext))]
    [Migration("20230112205323_Introduced invitation schema")]
    partial class Introducedinvitationschema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExpenseGroupMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseGroupMemberId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("ExpenseGroups");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Acceptance")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpenseGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvitationProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseGroupId");

                    b.HasIndex("InvitationProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ExpenseGroupInvitations");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpenseGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Paid")
                        .HasColumnType("money");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseGroupId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ExpenseGroupMembers");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("AzureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.Expense", b =>
                {
                    b.HasOne("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroupMember", null)
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseGroupMemberId");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroupInvitation", b =>
                {
                    b.HasOne("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroup", "ExpenseGroup")
                        .WithMany("expenseGroupInvitations")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TGC.CareShare.WebAPI.Models.DataModels.Profile", "InvitationProfile")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("InvitationProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TGC.CareShare.WebAPI.Models.DataModels.Profile", "Profile")
                        .WithMany("SentInvitations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExpenseGroup");

                    b.Navigation("InvitationProfile");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroupMember", b =>
                {
                    b.HasOne("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroup", "ExpenseGroup")
                        .WithMany("ExpenseGroupMembers")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TGC.CareShare.WebAPI.Models.DataModels.Profile", "Profile")
                        .WithMany("Memberships")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseGroup");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroup", b =>
                {
                    b.Navigation("ExpenseGroupMembers");

                    b.Navigation("expenseGroupInvitations");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.ExpenseGroupMember", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("TGC.CareShare.WebAPI.Models.DataModels.Profile", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });
#pragma warning restore 612, 618
        }
    }
}
